name: pip (macos-namespace)

on:
  workflow_dispatch:
  # pull_request:
  # push:
  #   # branches:
  #   #   - main

jobs:
  build:
    name: Build with pip
    runs-on: namespace-profile-mac-sequoia

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Set min macOS version
      if: runner.os == 'macOS'
      run: |
        echo "MACOS_DEPLOYMENT_TARGET=10.14" >> $GITHUB_ENV

    - name: Dependencies
      run: |
        pip install pip -U

    - name: Check versions
      run: |
        python --version
        pip --version
        cmake --version

    - name: Build and install kima
      run: |
        pip install --verbose .[test]

    - name: Test
      run: |
        python -m pytest -s tests/ 

    - name: Run benchmark
      run: |
        python -m pytest -s tests/test_benchmarks.py --benchmark-json output.json
